name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '24.x'
          
      - name: Configure Pages
        uses: actions/configure-pages@v5 # v5 en güncel sürümdür
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5 # v4.0.5 Node 24 runnerları için optimize edilmiştir
